# REST Client tests based on the Rest Client vscode extension
@hostname = http://localhost
@port = 3000
@host = {{hostname}}:{{port}}

### Test Posting user
# @name login
POST {{host}}/users HTTP/1.1
content-type: application/json

{
    "name": "test6",
    "age": 29,
	"password": "th3matr1x_20T"
}

### Test Getting user
GET {{host}}/users/all
content-type: application/json

### Test Getting user with Query
GET {{host}}/users/all?limit=1&offset=1
content-type: application/json

### Test Putting user
PUT {{host}}/users HTTP/1.1
content-type: application/json

{
    "name": "test3"
}

### Test Getting user
GET {{host}}/users/test
content-type: application/json

### Test Deleting user
DELETE  {{host}}/users/test2
content-type: application/json
