# REST Client tests based on the Rest Client vscode extension
@hostname = http://localhost
@port = 3000
@host = {{hostname}}:{{port}}
@userRoutePath = users

### Test creating new user
POST {{host}}/{{userRoutePath}} HTTP/1.1
content-type: application/json
roles: admin

{
    "name": "test7",
    "age": 29,
	"password": "th3matr1x_20T"
}

### Test creating new user with wrong role
POST {{host}}/{{userRoutePath}} HTTP/1.1
content-type: application/json
roles: guest

{
    "name": "test7",
    "age": 29,
	"password": "th3matr1x_20T"
}

### Test Getting all user
GET {{host}}/{{userRoutePath}}/all
content-type: application/json

### Test Getting users with wrong Query
GET {{host}}/{{userRoutePath}}/all?limit=a&offset=b
content-type: application/json

### Test Getting user with wrong offset & limit Queries
GET {{host}}/{{userRoutePath}}/all?limit=-1&offset=-1
content-type: application/json

### Test Getting user with proper queries
GET {{host}}/{{userRoutePath}}/all?limit=2&offset=1
content-type: application/json

### Test updating user
PUT {{host}}/{{userRoutePath}} HTTP/1.1
content-type: application/json

{
    "name": "test3"
}

### Test Getting user
GET {{host}}/{{userRoutePath}}/test
content-type: application/json

### Test Deleting user
DELETE  {{host}}/{{userRoutePath}}/test2
content-type: application/json
